# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  sam: circleci/aws-sam-serverless@3.2.0
  mabl: mabl/trigger-tests@1.0.8

jobs:
  E2Etest:
    docker:
      - image: cimg/base:stable
    steps:
      - mabl/run-tests:
          api-key: MABL_API_KEY
          application-id: o3HCI0VFVwmTjS1fJ5IX2A-a
          environment-id: bAZqzCIFqK0NbRZONMMrgQ-e


workflows:
  Release:
    jobs:
      - sam/deploy:
          name: Deploy_dev
          context: dev
          stack-name: stack-dev
          template: ./toolchain_lambda/template-dev.yaml
          s3-bucket: toolchain-artifacts
      - E2Etest:
          context: dev
          requires: 
            - Deploy_dev
      - sam/deploy:
          name: Deploy_prod
          context: dev
          requires: 
            - E2Etest
          stack-name: stack-prod
          template: ./toolchain_lambda/template-prod.yaml
          s3-bucket: toolchain-artifacts