# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  sam: circleci/aws-sam-serverless@3.2.0
  mabl: mabl/trigger-tests@1.0.8

jobs:
  E2Etest:
    docker:
      - image: cimg/base:stable
    # machine: true
    steps:
      - mabl/run-tests:
          api-key: MABL_API_KEY
          application-id: o3HCI0VFVwmTjS1fJ5IX2A-a
          environment-id: bAZqzCIFqK0NbRZONMMrgQ-e
    # docker:
    #   - image: cimg/base:stable
  # build:
    # docker:
    #   - image: cimg/base:stable
    # steps:
    #   - checkout
    #   - sam/install
    #   - run: sam build

  # say-hello:
  #   # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
  #   # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Say hello"
  #         command: | 
  #           echo "Hello, World!!"
  #           ls -la

workflows:
  Release:
    jobs:
      - sam/deploy:
          name: Deploy_dev
          context: dev
          stack-name: stack-dev
          template: ./toolchain_lambda/template-dev.yaml
          s3-bucket: toolchain-artifacts
          # s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-1iovfc7272jgf
      - E2Etest:
          context: dev
          requires: 
            - Deploy_dev
      - sam/deploy:
          name: Deploy_prod
          context: dev
          requires: 
            - E2Etest
          stack-name: stack-prod
          template: ./toolchain_lambda/template-prod.yaml
          s3-bucket: toolchain-artifacts
          # s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-1iovfc7272jgf