version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iovfc7272jgf"
s3_prefix = "sam-app"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
